### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by shaji-Dev** [phaux/babel-html#3]
Hi, first of all thank you for offering such a solution, it's what's missing from the Babel. 

Running the command "babel-html -s <source-file> -d <dest-file>" does not work, it's not even creating the destination file. There are no error messages neither, as if it was successful, but it's not.

Is there a fix for this or is it not supported anymore?

Thank you.

**Comment by phaux** [comment]
That's probably because your command is wrong. It should be:
```
babel-html -s sources/ -d destination/
```

**Comment by shaji-Dev** [comment]
I think I'm doing it right, in the terminal, I'm at the root project path "C:\Users\Shaji\WebstormProjects\MeasureMap\measure-map-web"

That I want to transpile is inside a folder called "app" inside the project folder. This the command I use for this particular case:

babel-html -s app/index-original.html -d app/index-compiled.html

**Comment by phaux** [comment]
No, you have to specify a directory. e.g. `babel-html -s app -d app-compiled`

**Comment by shaji-Dev** [comment]
Now it's working, thank you very much.
